### ISSUE TITLE
Segmentation Fault when reading Score from MIDI files

### ISSUE THREAD

**Issue by JLenzy** [Yikai-Liao/symusic#34]
I am getting Segmentation faults when attempting to read get Scores from this database:
https://zenodo.org/records/5120004#.Yhxr0-jMJBA

I am simply trying to read in all the MIDI files as scores when it occurs:

```
score_dict = {}
midi_files = list(Path(input_dir).glob("**/*.mid"))

fail_count = 0
for mf in tqdm(midi_files):
  try:
      name = str(Path(mf).stem)
      score = Score(mf)
  except Exception as e:
      fail_count = 1
```

Python simply returns:
`Segmentation fault`

After re-running multiple times, it seems to happen on different files each time. 
Following [this](https://stackoverflow.com/questions/10035541/what-causes-a-python-segmentation-fault) post I tried increasing my stack memory to 12,000 but that did not fix the issue

**Comment by Yikai-Liao** [comment]
Thanks for the feedback, I'll do further testing afterward. I'm a bit busy this week.

**Comment by JLenzy** [comment]
Hi @Yikai-Liao , I'm going to close this issue. Tried re-installing symusic and it sorted itself out.

**Comment by lzqlzzq** [comment]
Sorry for the inconvenience. The previous version of `minimidi` seems to have this flaw.
