### ISSUE TITLE
Make `Score.clip` include the ongoing tempo/time signature/key signature at `start`

### ISSUE THREAD

**Issue by Natooz** [Yikai-Liao/symusic#35]
Hello,

I have a small feature request for the `clip` method: make it include the current tempo, time signature and key signature at the tick `start`. The current implementation keeps the events of these types occurring within the clip section (i.e. changes), but we might not know what are the values of these features at the beginning of the clip.

**Describe the solution you'd like**

Make `clip` determine the latest tempo/time signature/key signature occurring before the `start` tick, and add `Tempo`/`TimeSignature`/`KeySignature` elements in the returned Score chunk with time values at `start_tick`.
This could set as an option controlled by a method attribute.

**Describe alternatives you've considered**

Here is how I implemented it in Python:

```Python
def extract_chunk_from_midi(
    midi: Score, tick_start: int, tick_end: int, clip_end: bool = False
) -> Score:
    """
    Extract a chunk of a ``Score``.

    The returned chunk will have a starting time at tick 0, i.e. the times of its
    events will be shifted by ``-tick_start``.

    :param midi: object to extract a chunk from.
    :param tick_start: starting tick of the chunk to extract.
    :param tick_end: ending tick of the chunk to extract.
    :param clip_end: if given ``True``, the chunk at ``tick_end + 1`` and thus include
        the events occurring at ``tick_end``. (default: ``False``)
    :return: chunk of the ``midi`` starting at ``tick_start and ending at ``tick_end``.
    """
    # Get the tempo, time sig and key sig at the beginning of the chunk to extract
    # There might not be default key signatures in the Score
    tempo, time_signature, key_signature = None, None, KeySignature(0, 0, 0)
    for tempo_ in midi.tempos:
        if tempo_.time > tick_start:
            break
        tempo = tempo_
    for time_signature_ in midi.time_signatures:
        if time_signature_.time > tick_start:
            break
        time_signature = time_signature_
    for key_signature_ in midi.key_signatures:
        if key_signature_.time > tick_start:
            break
        key_signature = key_signature_
    tempo.time = time_signature.time = key_signature.time = 0

    # Clip the MIDI and append the global attributes
    midi_split = midi.clip(tick_start, tick_end, clip_end=clip_end).shift_time(
        -tick_start
    )
    midi_split.tempos.append(tempo)
    midi_split.time_signatures.append(time_signature)
    midi_split.key_signatures.append(key_signature)

    return midi_split
```

I finally got back doing some c++ and got a glimpse of nanobind. If you want, I can try to implement this.

**Additional context**

That's something I'm implementing for this MidiTok PR: https://github.com/Natooz/MidiTok/pull/148

**Comment by Yikai-Liao** [comment]
I am recently preparing for the 3.24 gre exam. Sorry for not having time to read your requirements carefully. But you can try to modify the function if you are happy to do so.

**Comment by Yikai-Liao** [comment]
@Natooz I understand this issue. This probably won't involve a lot of modifications. I'll make the changes as soon as I can.

**Comment by Yikai-Liao** [comment]
I agree with you

**Comment by Yikai-Liao** [comment]
@Natooz I have modified the `clip` function. Does this work as what you expected?

![截图_20240327150316](https://github.com/Yikai-Liao/symusic/assets/110762732/b931dcb2-08d4-4e3d-8d1d-90f1bc2f805c)

**Comment by Natooz** [comment]
Absolutely! Thank you for these changes!

**Comment by Mintas** [comment]
@Yikai-Liao  Hello!
I have encountered the same problem =(
[](url)

Can you please help me to find commit that fixes the issue?
is it this one? https://github.com/Yikai-Liao/symusic/commit/68eb4f4a20c1e16e62a00848f2b5097eb4c9c109
If so , that does rly looks like clip_with_sentinel was removed from implementation during refactoring it the commit below:
see : [here it was](https://github.com/Yikai-Liao/symusic/commit/27a0501d07827d19d5c78e71c98bbf5c798d4d3d#diff-0be625c323cfde4bc9e5e3c7f967ed96a2886e26b2f88813dc617f6952f146ffL101)
and then [its gone](https://github.com/Yikai-Liao/symusic/commit/27a0501d07827d19d5c78e71c98bbf5c798d4d3d#diff-0be625c323cfde4bc9e5e3c7f967ed96a2886e26b2f88813dc617f6952f146ffR95) =( 

If this is the case, can you pls provide a fix for this?)

**Comment by Natooz** [comment]
Last time I checked/tested it worked as expected.

Can you provide a minimal code snippet + files resources allowing to reproduce the bug?

**Comment by Mintas** [comment]
```
def split_midi_up_to_bar_limit(bar_limit, midi_path, midi_output_path = None):
    score = symusic.Score.from_file(midi_path)

    #bar_ticks starting with 0 - left stove of first bar
    bar_ticks = miditok.utils.get_bars_ticks(score) 
    print(f'total_bars:{len(bar_ticks)} and first ticks are:{bar_ticks[0:3]}')
    starting_crop = score
    if len(bar_ticks) > bar_limit:
        bar_limit_tick = bar_ticks[bar_limit]
        starting_crop = **score.clip**(start=0, end=bar_limit_tick, clip_end=False, inplace=False)
        
    if midi_output_path is not None:
        #dump
        starting_crop.dump_midi(midi_output_path)
    return starting_crop

split_midi_up_to_bar_limit(80, "Symphony D759 n8 1mov ''Unfinished''.mid", "start_Symphony D759 n8 1mov ''Unfinished''.mid")

score_start_chunk = music21.converter.parse("start_Symphony D759 n8 1mov ''Unfinished''.mid")
key = score_start_chunk.analyze('AardenEssen')
```

https://bitmidi.com/symphony-d759-n8-1mov-unfinished-mid
