### ISSUE TITLE
MIDI with negative beginning tick

### ISSUE THREAD

**Issue by Natooz** [Yikai-Liao/symusic#37]
Hey, 👋

I encountered a case where a specific MIDI file from the Lakh dataset got it's first tick before 0.
[10e903c3aa7a6b6c5ce5a74d5cfb8702.mid.zip](https://github.com/Yikai-Liao/symusic/files/15048694/10e903c3aa7a6b6c5ce5a74d5cfb8702.mid.zip)

<img width="1010" alt="Screenshot 2024-04-20 at 17 06 00" src="https://github.com/Yikai-Liao/symusic/assets/56734983/0b8867c1-3c37-4a0c-b892-f3d066ce330c">

When inspecting tracks, the 14th (idx 13) note of the 19th (idx 18) track has a time at -4465856

```Python
for ti, track in enumerate(score.tracks):
    for ni, note in enumerate(track.notes):
        if note.time < 0:
            test = 0
```

Didn't have to to dig further yet, I'll just leave this open

**Comment by Yikai-Liao** [comment]
This looks like an int overflow is occurring, I'll check further.

**Comment by lzqlzzq** [comment]
Seems same problem occurred in `mido`.
![7PtCAzQKNS](https://github.com/Yikai-Liao/symusic/assets/79011287/bc7eea23-5348-477b-9108-3101d6ce6580)

**Comment by Natooz** [comment]
I found other MIDIs for which the `resample` operation shifts some of their events to negative time values
[midis.zip](https://github.com/Yikai-Liao/symusic/files/15138368/midis.zip)
They all have in common very large `end` tick values.

To reproduce:

```Python
from pathlib import Path
from symusic import Score

paths = list(Path("midis").glob("**/*.mid"))
for path in paths:
    score = Score(path)
    score = score.resample(12, min_dur=1)
    start_tick = score.start()
```

**Comment by Yikai-Liao** [comment]
@Natooz This is an int overflow caused by improper multiplication order during resample.

I've adjusted the order of multiplication in the resample and these examples no longer overflow. But an inappropriate resample can still cause an overflow, so I've further added an overflow check to determine if the scaled `time` is still valid.

**Comment by Natooz** [comment]
Wonderful thank you!
