### ISSUE TITLE
Suppression of Nanobind leak messages

### ISSUE THREAD

**Issue by JLenzy** [Yikai-Liao/symusic#43]
In the past week, I've been getting a huge increase in the number of nanobind leak messages. When trying to train a model (which is utilizing symusic via Miditok) it will finish with >1,000 leak messages from nanobind. 

It makes troubleshooting rather difficult, as it occupies so much of the terminal's recent history that I need to go through logs just to see what are the actual errors in my python code. 

From [this](https://nanobind.readthedocs.io/en/latest/faq.html) documentation I see there is an option to suppress the messages on the C++ side. Any chance this could be done for the public releases?

**Comment by Yikai-Liao** [comment]
What version of Python are you using? I've only seen this problem with Python 3.12. I've been trying to find what's causing these warnings, but haven't been able to pinpoint the exact problem. I agree that disabling these warnings would be a good idea first.

**Comment by JLenzy** [comment]
Currently on python 3.9

**Comment by Yikai-Liao** [comment]
Could you try the version on the main branch? I havn't find the memory leak info of this new version.

**Comment by Yikai-Liao** [comment]
And it would be better if you could find the minimum reproduction code

**Comment by Yikai-Liao** [comment]
The memory leak warnings are now disabled by default.

**Comment by JLenzy** [comment]
@Yikai-Liao excellent work, thank you very much!
