### ISSUE TITLE
安装时报错，报错信息如下

### ISSUE THREAD

**Issue by sunbeibei-hub** [Yikai-Liao/symusic#51]
系统版本：
centos7

报错信息如下：
Using cached pySmartDL-1.3.4-py3-none-any.whl (20 kB)
Building wheels for collected packages: symusic
  Building wheel for symusic (pyproject.toml): started
  Building wheel for symusic (pyproject.toml): finished with status 'error'
  error: subprocess-exited-with-error
  
  × Building wheel for symusic (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [12 lines of output]
      WARNING: Use cmake.version instead of cmake.minimum-version with scikit-build-core >= 0.8
      WARNING: Use ninja.version instead of ninja.minimum-version with scikit-build-core >= 0.8
      2024-08-24 17:43:46,959 - scikit_build_core - WARNING - cmake should not be in build-system.requires - scikit-build-core will inject it as needed
      2024-08-24 17:43:46,959 - scikit_build_core - WARNING - ninja should not be in build-system.requires - scikit-build-core will inject it as needed
      *** scikit-build-core 0.10.5 using CMake 3.30.2 (wheel)
      *** Configuring CMake...
      loading initial cache file /tmp/tmphyhgu4qb/build/CMakeInit.txt
      -- The C compiler identification is GNU 9.3.1
      -- The CXX compiler identification is GNU 9.3.1
      src/tcmalloc.cc:284] Attempt to free invalid pointer 0x3bfc040
      
      *** CMake configuration failed
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for symusic
Failed to build symusic
ERROR: ERROR: Failed to build installable wheels for some pyproject.toml based projects (symusic)
Traceback (most recent call last):
  File "/data/search/bei/ComfyUI/nodes.py", line 1993, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/data/search/bei/ComfyUI/custom_nodes/ComfyUI_VLM_nodes/__init__.py", line 40, in <module>
    check_requirements_installed(requirements_path)
  File "/data/search/bei/ComfyUI/custom_nodes/ComfyUI_VLM_nodes/__init__.py", line 35, in check_requirements_installed
    subprocess.check_call([sys.executable, '-s', '-m', 'pip', 'install', *missing_packages])
  File "/home/search/miniconda3/envs/bei_stab_d/lib/python3.10/subprocess.py", line 369, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/data/search/bei/SD/stable-diffusion-webui/venv/bin/python', '-s', '-m', 'pip', 'install', 'symusic']' returned non-zero exit status 1.

安装comfyui插件ComfyUI_VLM_nodes时的报错。

python env环境：
absl-py==2.0.0
accelerate==0.33.0
addict==2.4.0
aenum==3.1.15
aggdraw==1.3.18.post0
aiofiles==23.2.1
aiohttp==3.9.1
aiosignal==1.3.1
albumentations==1.3.1
aliyun-python-sdk-alimt==3.2.0
aliyun-python-sdk-core==2.13.10
aliyunsdkcore==1.0.3
altair==5.2.0
antlr4-python3-runtime==4.9.3
anyio==3.7.1
argostranslate==1.9.6
asttokens==2.4.1
async-timeout==4.0.3
asyncer==0.0.2
attrs==23.1.0
audioread==3.0.1
av==11.0.0
basicsr==1.4.2
beautifulsoup4==4.12.2
bidict==0.22.1
blend-modes==2.1.0
blendmodes==2022
blind-watermark==0.4.4
blinker==1.8.2
boto3==1.34.7
botocore==1.34.7
cachetools==5.3.2
certifi==2023.11.17
cffi==1.16.0
chardet==5.2.0
charset-normalizer==3.3.2
clean-fid==0.1.35
click==8.1.7
clip==1.0
clip-interrogator==0.6.0
cmake==3.30.2
color-matcher==0.5.0
coloredlogs==15.0.1
colorlog==6.8.0
colour-science==0.4.4
compel==2.0.2
contourpy==1.2.0
cryptography==41.0.7
cssselect2==0.7.0
cstr @ git+https://github.com/WASasquatch/cstr@0520c29a18a7a869a6e5983861d6f7a4c86f8e9b
ctranslate2==4.3.1
cupy-cuda12x==12.1.0
cycler==0.12.1
Cython==3.0.8
datasets==2.20.0
ddt==1.7.0
decorator==4.0.11
decord==0.6.0
deep-translator==1.11.4
deepdiff==6.7.1
deprecation==2.1.0
depth_anything @ https://github.com/huchenlei/Depth-Anything/releases/download/v1.0.0/depth_anything-2024.1.22.0-py2.py3-none-any.whl#sha256=26c1d38b8c3c306b4a2197d725a4b989ff65f7ebcf4fb5a96a1b6db7fbd56780diffusers==0.29.2
dill==0.3.7
diskcache==5.6.3
distro==1.9.0
docopt @ file:///data/search/bei/ComfyUI/custom_nodes/ComfyUI_LayerStyle/whl/docopt-0.6.2-py2.py3-none-any.whl#sha256=15fde8252aa9f2804171014d50d069ffbf42c7a50b7d74bcbb82bfd5700fcfc2
docutils==0.20.1
easydict==1.11
einops==0.8.0
evalidate==2.0.3
exceptiongroup==1.2.0
executing==2.0.1
facexlib==0.3.0
fairscale==0.4.13
fastapi==0.94.0
fastrlock==0.8.2
ffmpeg-python==0.2.0
ffmpy @ git+https://github.com/WASasquatch/ffmpy.git@f000737698b387ffaeab7cd871b0e9185811230d
filelock==3.13.1
filetype==1.2.0
filterpy==1.4.5
flatbuffers==23.5.26
fonttools==4.47.0
frozenlist==1.4.1
fsspec==2023.12.2
ftfy==6.1.3
future==0.18.3
fvcore==0.1.5.post20221221
gdown==4.7.1
gfpgan==1.3.8
gitdb==4.0.11
GitPython==3.1.32
google-ai-generativelanguage==0.6.6
google-api-core==2.19.1
google-api-python-client==2.142.0
google-auth==2.25.2
google-auth-httplib2==0.2.0
google-auth-oauthlib==1.2.0
google-generativeai==0.7.2
googleapis-common-protos==1.63.2
googletrans-py==4.0.0
gradio==3.41.2
gradio_client==0.5.0
gray2color==0.4.3
grpcio==1.66.0
grpcio-status==1.62.3
h11==0.12.0
h2==4.1.0
handrefinerportable @ https://github.com/huchenlei/HandRefinerPortable/releases/download/v1.0.1/handrefinerportable-2024.2.12.0-py2.py3-none-any.whl#sha256=1e6c702905919f4c49bcb2db7b20d334e8458a7555cd57630600584ec38ca6a9
hpack==4.0.0
httpcore==0.15.0
httplib2==0.22.0
httpx==0.24.1
huggingface-hub==0.23.3
humanfriendly==10.0
hyperframe==6.0.1
idna==3.6
image-reward==1.5
ImageHash==4.3.1
imageio==2.34.2
imageio-ffmpeg==0.4.9
img2texture @ git+https://github.com/WASasquatch/img2texture.git@a546609a915caf1dcb84a15bf44b5b639ad924e6
importlib-metadata==7.0.0
importlib-resources==6.1.1
inflection==0.5.1
insightface==0.7.3
iopath==0.1.9
ipython==8.19.0
jax==0.4.30
jaxlib==0.4.30
jedi==0.19.1
Jinja2==3.1.2
jmespath==0.10.0
joblib==1.3.2
json_repair==0.28.3
jsonmerge==1.8.0
jsonschema==4.20.0
jsonschema-specifications==2023.11.2
kiwisolver==1.4.5
kornia==0.7.3
kornia_rs==0.1.2
lark==1.1.2
lark-parser==0.12.0
lazy_loader==0.3
librosa==0.10.1
lightning-utilities==0.10.0
lit==17.0.6
llvmlite==0.41.1
lmdb==1.4.1
loguru==0.7.2
lpips==0.1.4
lxml==4.9.4
mapbox-earcut==1.0.1
Markdown==3.5.1
markdown-it-py==3.0.0
MarkupSafe==2.1.3
matplotlib==3.8.2
matplotlib-inline==0.1.6
matrix-client==0.4.0
mdurl==0.1.2
mediapipe==0.10.13
ml-dtypes==0.4.0
moviepy==1.0.3
mpmath==1.3.0
msgpack==1.0.7
mss==9.0.1
multidict==6.0.4
multiprocess==0.70.15
natsort==8.4.0
networkx==3.2.1
numba==0.58.1
numexpr==2.8.8
numpy==1.23.5
nvidia-cublas-cu12==12.1.3.1
nvidia-cuda-cupti-cu12==12.1.105
nvidia-cuda-nvrtc-cu12==12.1.105
nvidia-cuda-runtime-cu12==12.1.105
nvidia-cudnn-cu12==9.1.0.70
nvidia-cufft-cu12==11.0.2.54
nvidia-curand-cu12==10.3.2.106
nvidia-cusolver-cu12==11.4.5.107
nvidia-cusparse-cu12==12.1.0.106
nvidia-nccl-cu12==2.20.5
nvidia-nvjitlink-cu12==12.4.99
nvidia-nvtx-cu12==12.1.105
oauthlib==3.2.2
omegaconf==2.2.3
onnx==1.15.0
onnxruntime==1.16.3
onnxruntime-gpu==1.16.3
open-clip-torch==2.20.0
openai==1.6.1
openai-clip==1.0.1

**Comment by Yikai-Liao** [comment]
You need newer gcc(>=12) or clang(>=14), see https://github.com/Natooz/MidiTok/issues/155#issuecomment-2027122797

请使用新版本的gcc(>=12)或者clang(>=14)，详见 https://github.com/Natooz/MidiTok/issues/155#issuecomment-2027122797

**Comment by sunbeibei-hub** [comment]
Thank you, I'm going to try it！

> You need newer gcc(>=12) or clang(>=14), see [Natooz/MidiTok#155 (comment)](https://github.com/Natooz/MidiTok/issues/155#issuecomment-2027122797)
> 
> The libstdc++ and kernel is too old in CentOS, and the precompiled verison (by github action) could not support it. So pypi will compile symusic from sourece. I have test the compilation on Rocky Linux (similar to CentOS), and it works fine with the clang installed in conda.
> 
> 请使用新版本的gcc(>=12)或者clang(>=14)，详见 [Natooz/MidiTok#155 (comment)](https://github.com/Natooz/MidiTok/issues/155#issuecomment-2027122797) CentOS的libstdc++和内核版本太老了，导致其无法安装再github action中预编译的安装包。所以pypi会自动使用源代码编译。我已经再一台Rocky Linux (类似于CentOS) 的服务器上测试过 symusic的编译，在使用conda中安装的clang的情况下可以正常安装。

**Comment by sunbeibei-hub** [comment]
> You need newer gcc(>=12) or clang(>=14), see [Natooz/MidiTok#155 (comment)](https://github.com/Natooz/MidiTok/issues/155#issuecomment-2027122797)
> 
> The libstdc++ and kernel is too old in CentOS, and the precompiled verison (by github action) could not support it. So pypi will compile symusic from sourece. I have test the compilation on Rocky Linux (similar to CentOS), and it works fine with the clang installed in conda.
> 
> 请使用新版本的gcc(>=12)或者clang(>=14)，详见 [Natooz/MidiTok#155 (comment)](https://github.com/Natooz/MidiTok/issues/155#issuecomment-2027122797) CentOS的libstdc++和内核版本太老了，导致其无法安装再github action中预编译的安装包。所以pypi会自动使用源代码编译。我已经再一台Rocky Linux (类似于CentOS) 的服务器上测试过 symusic的编译，在使用conda中安装的clang的情况下可以正常安装。


我更新了gcc版本到12.2 ， clang版本到17.0，但是安装时依然会报错

报错信息：
Building wheels for collected packages: symusic
  Building wheel for symusic (pyproject.toml) ... error
  error: subprocess-exited-with-error
  
  × Building wheel for symusic (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [12 lines of output]
      WARNING: Use cmake.version instead of cmake.minimum-version with scikit-build-core >= 0.8
      WARNING: Use ninja.version instead of ninja.minimum-version with scikit-build-core >= 0.8
      2024-08-30 16:43:46,711 - scikit_build_core - WARNING - cmake should not be in build-system.requires - scikit-build-core will inject it as needed
      2024-08-30 16:43:46,711 - scikit_build_core - WARNING - ninja should not be in build-system.requires - scikit-build-core will inject it as needed
      *** scikit-build-core 0.10.5 using CMake 3.30.2 (wheel)
      *** Configuring CMake...
      loading initial cache file /tmp/tmp26quohiz/build/CMakeInit.txt
      -- The C compiler identification is GNU 12.2.0
      -- The CXX compiler identification is GNU 12.2.0
      src/tcmalloc.cc:284] Attempt to free invalid pointer 0x3070040
      
      *** CMake configuration failed
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for symusic
Failed to build symusic
ERROR: ERROR: Failed to build installable wheels for some pyproject.toml based projects (symusic)




我的clang版本：
pip show clang
WARNING: Ignoring invalid distribution -ltralytics (/data/search/bei/SD/stable-diffusion-webui/venv/lib/python3.10/site-packages)
WARNING: Ignoring invalid distribution -rotobuf (/data/search/bei/SD/stable-diffusion-webui/venv/lib/python3.10/site-packages)
Name: clang
Version: 17.0.6
Summary: libclang python bindings
Home-page: http://clang.llvm.org/
Author: LLVM team - pypi upload by Loic Jaquemet
Author-email: 
License: Apache-2.0 with LLVM exception
Location: /data/search/bei/SD/stable-diffusion-webui/venv/lib/python3.10/site-packages
Requires: 
Required-by:

**Comment by lzqlzzq** [comment]
This seems to be a problem with `stable-diffusion`, not `symusic`...
You can try solution of https://github.com/TheLastBen/fast-stable-diffusion/issues/2343#issuecomment-1642699339.

**Comment by sunbeibei-hub** [comment]
> This seems to be a problem with `stable-diffusion`, not `symusic`... You can try solution of [TheLastBen/fast-stable-diffusion#2343 (comment)](https://github.com/TheLastBen/fast-stable-diffusion/issues/2343#issuecomment-1642699339).

thank you ,i will try it

**Comment by Yikai-Liao** [comment]
By the way, you are using gcc12, not clang.
> -- The C compiler identification is GNU 12.2.0
> -- The CXX compiler identification is GNU 12.2.0

**Comment by sunbeibei-hub** [comment]
> By the way, you are using gcc12, not clang.
> 
> > -- The C compiler identification is GNU 12.2.0
> > -- The CXX compiler identification is GNU 12.2.0

is this  why i get error??

**Comment by Yikai-Liao** [comment]
> is this why i get error??
I don't know.
