### ISSUE TITLE
Filter method is no-op

### ISSUE THREAD

**Issue by ilya16** [Yikai-Liao/symusic#52]
`.filter()` method does not filter the elements in `symusic==0.5.2`

Simple code to check:
```
notes = score.tracks[0].notes.copy()
notes1 = notes.filter(lambda x: x.pitch < 60, inplace=False)
notes2 = notes.filter(lambda x: x.pitch >= 60, inplace=False)
```

**Comment by Yikai-Liao** [comment]
Thans for your feed back. I find that a `nb::cast<bool>` is missing in the implementation of `filter`. I have fixed this.

**Comment by ilya16** [comment]
@Yikai-Liao thank you for the quick fix!
