### ISSUE TITLE
Tempo value mismatch

### ISSUE THREAD

**Issue by Natooz** [Yikai-Liao/symusic#9]
Following #6, there is a float conversion somewhere that can slightly alter the `Tempo.tempo` values, causing the tests (`__eq__`) to fail.

**Comment by Yikai-Liao** [comment]
One possible solution is to store the origin value（int） in Midi tempo event， and make bpm (float) a property  that is calculated at the time of the call.

**Comment by Natooz** [comment]
It could be solve the issue indeed!
Maybe a good solution would be to keep the original int value private, and subclass `__eq__` to only check it and `.time`, and omitting `.tempo`?
